CREATE DATABASE  myLoginsystem;

CREATE TABLE users (
id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY NOT NULL,
user_name TINYTEXT NOT NULL,
emailuser TINYTEXT NOT NULL,
pwdUser LONGTEXT NOT NULL 
);